name: Update-Box86

# Controls when the workflow will run
on:
  #schedule:
  #   - cron: '0 */6 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-box86:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install wget git build-essential python3 make gettext pinentry-tty sudo devscripts dpkg-dev -y

      # import gpg key
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: List GPG keys
        run: gpg -K

      # generate a deb
      - name: Set up multiarch/qemu-user-static
        run: |
          docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - uses: docker://multiarch/ubuntu-core:armhf-bionic
        with:
          args: >
            bash /github/workspace/create-deb.sh
            
      - name: Write new package to repo
        run: |
          export DIRECTORY="$GITHUB_WORKSPACE"
          cd $DIRECTORY/debian
          rm $DIRECTORY/debian/Packages || echo "Failed to remove packages file"
          rm $DIRECTORY/debian/Packages.gz || echo "Failed to remove packages.gz file"
          rm $DIRECTORY/debian/Release || echo "Failed to remove release file"
          rm $DIRECTORY/debian/Release.gpg || echo "Failed to remove release.gpg file"
          rm $DIRECTORY/debian/InRelease || echo "Failed to remove inrelease file"
          dpkg-scanpackages --multiversion . > Packages
          gzip -k -f Packages
          apt-ftparchive release . > Release
          gpg --default-key "itainelken@gmail.com" --batch --pinentry-mode="loopback" --passphrase="${{ secrets.PASSPHRASE }}" -abs -o - Release > Release.gpg || error "failed to sign Release.gpg with gpg "
          gpg --default-key "itainelken@gmail.com" --batch --pinentry-mode="loopback" --passphrase="${{ secrets.PASSPHRASE }}" --clearsign -o - Release > InRelease || error "failed to sign InRelease with gpg"

      - name: Upload
        run: |
          cd $GITHUB_WORKSPACE
          git config --global user.email "itainelken@gmail.com"
          git config --global user.name "Itai-Nelken"
          git add .
          git commit -m "Update box86 to commit $(cat commit.txt)" 
          git push
